# Generated by Django 4.0 on 2022-01-04 23:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_extension_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='extension',
            name='public',
            field=models.BooleanField(default=True),
        ),
    ]
