# Generated by Django 4.0 on 2022-01-03 03:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('start', models.DateTimeField()),
                ('end', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Extension',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField()),
                ('name', models.CharField(max_length=255)),
                ('extension_type', models.CharField(choices=[('sip', 'Sip'), ('dect', 'Dect'), ('callgroup', 'Callgroup')], default='sip', max_length=255)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='extensions', to='base.event')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auth.user')),
            ],
        ),
        migrations.CreateModel(
            name='CallgroupMembership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accepted', models.BooleanField(default=False)),
                ('paused', models.BooleanField(default=False)),
                ('callgroup', models.ForeignKey(limit_choices_to={'extension_type': 'callgroup'}, on_delete=django.db.models.deletion.CASCADE, related_name='members', to='base.extension')),
                ('extension', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='callgroups', to='base.extension')),
            ],
        ),
    ]
