# Generated by Django 4.0 on 2022-01-03 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='extension',
            name='password',
            field=models.CharField(default='wijaraeQu5Oo2Yoh', max_length=16),
            preserve_default=False,
        ),
    ]
