# Generated by Django 4.0 on 2022-05-24 22:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    replaces = [('base', '0006_rename_password_extension_sip_password_and_more'), ('base', '0007_extension_dect_handset'), ('base', '0008_rename_imei_decthandset_ipei'), ('base', '0009_alter_decthandset_owner_alter_extension_owner'), ('base', '0010_alter_extension_sip_password'), ('base', '0011_rename_claim_token_extension_dect_claim_token'), ('base', '0012_extension_trunk')]

    dependencies = [
        ('base', '0005_alter_extension_extension_type_and_more'),
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.RenameField(
            model_name='extension',
            old_name='password',
            new_name='sip_password',
        ),
        migrations.AddField(
            model_name='extension',
            name='dialout_allowed',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='extension',
            name='outgoing_extension',
            field=models.CharField(blank=True, max_length=15),
        ),
        migrations.AddField(
            model_name='extension',
            name='static_target',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.CreateModel(
            name='DectHandset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ipei', models.CharField(max_length=32)),
                ('name', models.CharField(blank=True, max_length=255)),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='auth.user')),
            ],
        ),
        migrations.AddField(
            model_name='extension',
            name='dect_handset',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='extensions', to='base.decthandset'),
        ),
        migrations.AlterField(
            model_name='extension',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='auth.user'),
        ),
        migrations.AlterField(
            model_name='extension',
            name='sip_password',
            field=models.CharField(blank=True, max_length=16),
        ),
        migrations.AddField(
            model_name='extension',
            name='dect_claim_token',
            field=models.CharField(blank=True, max_length=15),
        ),
        migrations.AddField(
            model_name='extension',
            name='trunk',
            field=models.BooleanField(default=False),
        ),
    ]
