# Generated by Django 4.0 on 2022-05-24 22:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_rename_password_extension_sip_password_and_more_squashed_0012_extension_trunk'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='extension',
            constraint=models.UniqueConstraint(fields=('event', 'dect_handset'), name='unique_handset'),
        ),
    ]
