# Generated by Django 4.0 on 2022-07-10 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0007_extension_unique_handset'),
    ]

    operations = [
        migrations.AlterField(
            model_name='extension',
            name='extension_type',
            field=models.CharField(choices=[('sip', 'Sip'), ('dect', 'Dect'), ('callgroup', 'Callgroup'), ('static', 'Static'), ('temp', 'Temp')], default='sip', max_length=255),
        ),
    ]
